src/commands/math/basicSymbols.js

~ is in our font while &sim; isn't. fixes visual display of squiggle
while leaving the correct LaTex output

update tilde html output

---

src/services/saneKeyboardEvents.util.js

textareas have a select method but spans do not. check for the existence of this method
before executing it. fixes non-user-visible thrown error.

Fix select on ipad

---

src/css/textarea.less

could only repro when 'f' is the first character in the desmos calculator,
and only in chrome canary. seems like a non-destructive fix.
fix discovered by @ctlusto

Fix bleeding edge chrome bug

---

src/tree.js

`jQ.add` sorts the collection it outputs according to document order each time
it is called, so building a collection by folding `jQ.add` directly takes more
than quadratic time in the number of elements.
See the definition of `add` in jQuery 2.1.4
https://github.com/jquery/jquery/blob/2.1.4/src/traversing.js#L112
Here's a jsbin that demonstrates the problem, by timing rendering on
successively larger inputs:
http://jsbin.com/qeseye/edit?js,output
In order for this jsbin to work, you need to build mathquill with `make basic`,
and then serve the build folder on port 8000 (I do this with
`python -m SimpleHTTPServer`, run from the build folder).
Here are the timing results, before and after the change in this commit:
before:
```
n  time (ms)
1, 1.8968580000000088
2, 1.995256999999981
5, …
```

Fix quadratic jQ.add fold in fragment construction.

---

src/commands/math/basicSymbols.js

Fixes parsing copypasted `\operatorname{ans}`.

Allow commands inside \operatorname.

---

src/commands/math/commands.js

Just need to pass the 3rd optional 'text' argument. If we wanted the mathspeak to be different from the text output, we could pass that as a 4th optional argument.

Fix mathspeak for ans.

---

src/commands/math.js

Don't add spaces to mathSpeak array when decimal is encountered

---

src/commands/math/basicSymbols.js

Only want to override operatorname behavior for special commands
(like ans), not for "built in operator names" like lcm or arcsinh,
because the built in OperatorName rule can't have '.html()' called on
it (because it's missing .htmlTemplate).

Fix missing html template for built in operator names.

---

src/publicapi.js
src/services/saneKeyboardEvents.util.js
src/services/textarea.js
test/unit/publicapi.test.js
test/visual.html

Lets API consumers override the keyboard events abstraction with a
wrapper around `saneKeyboardEvents()` that can intercept events and ignore
them or do stuff like insert `ans` before a `+` is typed.

`substituteKeyboardEvents` config option

---

package.json

PJs 5.0.0 introduced a new behavior for this.constructor(...) in order
to be compatible with coffeescript classes. The new behavior means
that, if you don't use `new` when you call `this.constructor`, the
object this is an alias of `this` instead of a new object.
This behavior interacts badly with MathQuill's use of PJs to subclass
jQuery, and jQuery's use of `this.constructor` inside `pushStack`:
https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/core.js#L72-L84

PJs 5.0.0+ is currently incompatible with MathQuill.

---

src/services/saneKeyboardEvents.util.js

I'm not sure exactly why this fixes the problem, but it does. I don't know if this introduces a different problem. This is a lot closer to the original copy behavior before the saneKeyboardEvents PR.
@laughinghan - any objections here? I think I understand the problem with "cut" but I don't understand why "copy" needs to be or even should be called async. Introduced here: https://github.com/desmosinc/mathquill/pull/30/commits/702d2fcc0e6e7dae88c84b35db206ba9ab95f87d

unbreak copy. maximum call stack size exceeded

---

src/commands/math/basicSymbols.js
test/unit/ans.test.js

Fixes some edge cases like pasting in `\operatorname{pm}` by scoping special behavior to `ans` only.

Special case ans

---

src/css/textarea.less

Cherry-pick of upstream https://github.com/mathquill/mathquill/pull/687
Fixes #686. I have no idea why box-sizing: border box would cause
problems here; I discovered this by bisecting the problem to
058297a18e17e4aba09f738

Fix copying math in Safari

---

src/commands/math.js

Apple voices in VoiceOver (such as Alex, Bruce, and Victoria) do
some strange pronunciation given certain expressions,
e.g. "y-2" is spoken as "ee minus 2" (as if the y is short).
Not an ideal work-around, but placing quotation marks around
non-numeric vanilla symbols works. This will be reported to Apple.

Wrap non-numeric vanilla symbol mathspeak in quotes

---

src/commands/math/commands.js
src/services/aria.js

This improves how functions using summation notation are voiced with a screen reader including sums, products, coproducts, and integrals by announcing the command name and its bounds. (Before, we would intersperse "undefined" when reading these fields.)

Add mathspeak to items using summation notation

---

src/commands/math/commands.js
src/intro.js
src/publicapi.js
src/services/latex.js
src/services/mouse.js
src/tree.js

Eliminates the Node.byId dictionary. It replaces it with a temporary dictionary used for holding the Node until it gets linked to the DOM Element. Currently, that dictionary is being wiped on an interval. Ideally we'd be wiping it after each update cycle. I'm not sure where update cycles start and stop so I'm not attempting to make that change.
When we try to find the Node associated with a DOM Element we first check if it has a 'mathquill-command-id' or 'mathquill-block-id'. If so, we lookup the Node based on the id. We remove the property and store an expando property that links directly to the Node. This step is necessary because mathquill creates the entire html structure upfront rather than creating things piece by piece.
I think there's a chance this entire process could be greatly …

Use expando to link from DOM nodes to mathquill Nodes

---

src/services/aria.js

Fixes a problem where Narrator in Windows 10 announces 'group' before speaking text

Change ARIA alert element to paragraph

---

src/services/keystroke.js
test/unit/typing.test.js

There were two problems here:
1. dir was passed into ctrlDeleteDir, but was ignored, so Ctrl-Del
behaved the same as Ctrl-Backspace.
2. dir was not being passed to deleteDir in the short-circuit case,
which caused a prayer that expected a direction in deleteDir to fail.
Adds some test coverage to both the non-empty and empty-cases of
ctrlDeleteDir.

Fix Ctrl-Backspace and Ctrl-Del.

---

src/commands/math.js
src/services/focusBlur.js
src/services/textarea.js
src/tree.js
test/unit/aria.test.js
test/unit/html.test.js
test/unit/publicapi.test.js

This isn't ultimately ideal, because it doesn't allow users of screen readers to explore the math tree when reviewing MathQuill contents in their virtual exploration modes (like they can with MathML), but it is better than the mix of HTML and LaTeX that was shown before.
Especially useful for static math as its output is now consistent regardless of whether the user is directly interacting with MathQuill.

Use verbal mathspeak representations for MathQuill DOM text for screen reader users

---

src/services/keystroke.js

The second key is needed because Mac browsers intercept commands using = for changing text size/zoom level.

Add Ctrl-Alt-= and Ctrl-Alt-Shift-Right to speak evaluation

---

src/services/latex.js
src/services/mouse.js

Fixes a problem where if a write happens while the mouse is down, the
"cursor" can become invalid, and attempts to manipulate its selection
can throw errors.
Alternative to #60 that uses mathquill's existing notification system. There's some precedent for this in that notifications are used to invalidate the upDownCache in `keystroke.js`.
This is a broader fix for the same bug as in https://github.com/desmosinc/knox/pull/7492 that doesn't require being careful to avoid writing to mathquill when a selection is in progress.
In most cases, I think we actually do want to avoid writing to mathquill while a selection is in progress, but if we forget, it's better not to do invalid operations to the tree because these lead to subtle bugs that may only show up later.

Fix updating stale selections.

---

src/commands/math/basicSymbols.js
test/unit/typing.test.js

Adds a new API configuration, autoParenthesizedFunctions, that takes a space delimited list of functions that will auto parenthesize.
Behavior: when you finish typing one of those functions, we add parentheses. For example, typing "sin" will give "sin()." Note: completing a function in the middle, e.g. typing "sn" and then "i" won't insert the parens after the i or the n.

Add autoParenthesizedFunctions

---

src/services/latex.js

This is done primarily for static math instances whose LaTeX could change, such as when in Braille input mode in the scientific calculator or inside activities.

Update mathspeak ARIA label in renderLatex function

---

src/cursor.js
src/services/keystroke.js

Tracked the issue down to the fact that cursor.show() was being called
earlier after a renderLatexMath call than it previously was, because of
the newly added 'edit' notification.
I'm not totally sure why this was causing an issue in IE but not in
other browsers, but we can work around the problem by avoiding calling
'show' for the first time in response to an 'edit' notification.
The issue this fixes was introduced by #61

Fix missing cursor in ie

---

src/commands/math.js
src/commands/math/basicSymbols.js
src/services/focusBlur.js
test/basic.html
test/demo.html
test/unit/aria.test.js
test/unit/publicapi.test.js
test/visual.html

This dramatically improves the time it takes for the text() and mathspeak() methods to compute and return a meaningful result. Mathspeak was calling text multiple times per math block, and text itself would call a child's text method twice per iteration-- both combined to yield some dreadful performance bottlenecks when dealing with many nested structures, like 30 square roots. Mathspeak doesn't rely on text() at all now, and text() is guaranteed to call its child's method only once.
In the case of mathspeak, resulting verbal output is slightly different than it was previously, but I feel it's now what we intended it to be-- not pretty to read, but good for a speech synthesizer.

Improve mathspeak and text computation speeds

---

src/services/latex.js
src/tree.js

Creating a mathquill Fragment is expensive because it initializes a
jQuery datastructure to represent the fragment. Fragment also exposes
some useful iteration methods, and so mathquill creates a Fragment
whenever it needs to iterate over a group of nodes. This does a lot
more work than necessary in cases when the jQuery datastructure will
never be used: for example, serializing to latex, text, or mathspeak.
After this change, the time it takes to serialize a 20 digit number to
latex or mathspeak drops by almost an order of magnitude, from about
200 microseconds to about 30 microseconds.
The time it takes to serialize a 20-fold nested square root drops from
about 800 microseconds to about 80 microseconds.
Note: also replaced the implementations of Fragment's each and fold
to match the new …

Reduce amount of work that child iteration does.

---

src/commands/math.js
src/commands/math/basicSymbols.js
src/commands/math/commands.js
src/commands/text.js
src/intro.js
src/publicapi.js
src/services/focusBlur.js
src/services/keystroke.js
src/services/latex.js
src/services/textarea.js
src/tree.js
test/unit/latex.test.js

They're pretty bad for performance because they make more things
polymorphic and they make it harder for the compiler to analyze which
functions are being called. I think this diff shows that they don't
actually buy you all that much.
Note: builds on #70.

Remove MQ's functional helpers.

---

src/commands/math.js
src/commands/math/basicSymbols.js
src/cursor.js
src/services/keystroke.js
test/unit/aria.test.js
test/unit/publicapi.test.js

Example:
1.  Set MathQuill to y=\sqrt{x}.
2.  Select all.
Before, the mathspeak representation would run together and sound like gibberish.
Note: I opted not to process auto operator names like we do in the root.mathspeak function (e.g. where we replace things like "sin" with "sine"), because when selecting, I think hearing the actual letters "s i n" is more straight-forward.

Improve what is spoken when selecting text

---

src/services/latex.js
src/services/mouse.js
src/tree.js

We check if the request latex and the previous latex are in a form that we can efficiently and
safely mutate. Basically, we look for a number at the end of the latex. If both the previous and the
current latex have the same prefix before that number then we can skip to just updating the number.
The minus sign adds a ton of code complexity here. I decided to implement it 'correctly' because the
PlusMinus symbol is different than the Digit symbol. It has logic to decide if it's a binary
operator, and it could possibly add even more functionality. It probably isn't a good idea to
repurpose a PlusMinus node for a Digit node.
Once we deal with adding or removing the minus symbol, we start repurposing as many nodes as
possible by simply writing new digits in them. After that we decide if we …

Optimize slider update

---

src/commands/math.js
src/services/latex.js
src/services/textarea.js
test/unit/aria.test.js

Useful in some rare cases, such as identifying readonly table cells in the Desmos graphing calculator.

Allow static math fields to include a user-defineable ARIA label

---

src/services/focusBlur.js
src/services/scrollHoriz.js
test/unit/scrollHoriz.test.js

Bakes into mathquill a couple of behavior improvements.
(1) when you blur a mathquill, we scroll back to the beginning
(2) we add classes to the root block indicating if the contents are scrolled right or left
Mathquill doesn't do anything with those classes, just provide them for the rendering convenience of the consumer. I don't think this should introduce bad performance issues (the scrollHoriz logic is heavier), but would welcome a weigh-in.
TODO:

Update horizontal scroll behavior

---

src/services/focusBlur.js
src/services/textarea.js

Without this invalidation, a previous request to set selection can
cause focus to move back to a mathquill after it has already been moved
somewhere else.

Blur invalidates request to update selection.

---

src/cursor.js
src/services/focusBlur.js
src/services/latex.js

This fixes a prayer bug where I wasn't resetting the cursor.parent back to the root

add cursor.resetToEnd() method

---

src/commands/text.js

TextBox base class overrides the subclass ctrlSeq of "\textit" to "\text". This applied to other sub classes such as "\textsf" and etc.

fix latex for textit command

---

src/commands/math/basicSymbols.js
test/unit/typing.test.js

Fixes a problem where MathQuill would not report certain types of inequality symbols verbally, e.g. the <=, >=, ≤, and ≥.

Add mathspeak to inequality symbols

---

src/commands/text.js
src/services/keystroke.js
test/unit/text.test.js

* Reads aloud the content of text blocks (including via navigation). Also extends to formatting commands.
* Pulls in the HTML function change made to the MakeTextBlock function from #89.
* Adds HTML subclass unit test.

Text command improvements

---

src/commands/math/commands.js
test/unit/typing.test.js

Discovered there were issues with this command based on a conversation with a new blind Desmos user over the weekend.

Add verbal support for reading and navigating nthroots

---

src/services/saneKeyboardEvents.util.js
src/services/textarea.js

This isn't a recommended flag, but some customers may need this feature disabled for test security reasons.
Also fixes a bug with scrollHoriz. Paste (when allowed) now also triggers scrollHoriz.

Add a configuration flag to disable copy & paste

---

package.json

less version 3.0.0 causes problems with inline javascript, which was breaking the build

update less version dependency

---

src/services/keystroke.js

We were trying to index into, e.g., `parent.parent.ends[L]`, but it's
possible that a parent is actually equal to `0`, in which case there
is no `ends` property and the lookup throws. Reported by a partner,
but we're also seeing this occasionally on WWW.

Add defensive checks for property lookup on parent-parent nodes

---

package-lock.json

This is a new feature of npm that specifies exact package versions. It
gets generated every time you run `npm install` (or `make` or
`make basic`), so we need to either check this in or ignore it.
Checking it in is helpful because it avoid surprise version differences
between users.

Check in package-lock.

---

src/services/textarea.js
test/unit/publicapi.test.js
test/visual.html

It is not recommended to use this code because it can throw unexpected errors. I'm restoring it simply to restore backwards compatibility. The recommended api to use is the overrideTypedText and overrideKeystroke options.
The legacy (and buggy) way:
```
var mq = MQ.MathField(elt, {
substituteKeyboardEvents: function(textarea, handlers) {
return MQ.saneKeyboardEvents(textarea, $.extend({}, handlers, {
typedText: function (text) {
// snoop on the typedText here
mq.typedText(text); // leave this line out if you want to disable the typedText
},
keystroke: function (text) {
// snoop on the keystroke here
mq.keystroke(key); // leave this line out if you want to disable the keystroke
}
}));
}
});
```
The recommended way:
```
var mq = MQ.MathField(elt, {
overrideTypedText: function (text) {
// …
```

restore legacy substituteKeyboartdEvents option

---

docs/Api_Methods.md
src/commands/math.js
src/controller.js
src/publicapi.js
src/services/latex.js
src/services/textarea.js
test/unit/aria.test.js
test/unit/publicapi.test.js

* Changes the default ARIA label for MathQuill to "Math Input"
* Moves the logic for voicing ARIA alerts into the component itself. This will make MQ speech improvements much easier in activity builder.

ARIA Label Refinements

---

src/commands/math/commands.js

We were previously setting the label only when the initial MathBlock tree was constructed due to LaTeX being set externally. It now occurs in the finalizeTree method which makes navigating through summation notation through the calculator much easier to comprehend with a screen reader.
Example: instead of hearing "sum" as you move between the lower and upper bounds, you now consistently hear "start/end of lower/upper bound."

Improve ARIA label assignment for lower and upper bounds in summation notation

---

src/commands/math.js
src/css/math.less
src/tree.js

This works. It'd be better if we added the `mq-empty-parens` class while parsing instead of on blur, but I don't know how to make that happen. If anyone can point me to where to make that change I can make it. This feels good enough, though. It's guarded behind the already existent .isEmpty() check so it shouldn't really cause any performance issues.

hide the gray rectangle within empty parens

---

src/services/saneKeyboardEvents.util.js

IE11 won't allow you to call .select() on a hidden textarea.

fix "Incorrect Function" error

---

src/services/saneKeyboardEvents.util.js
test/unit/saneKeyboardEvents.test.js

We are seeing cases where blur is tricking mathquill into thinking there was a keypress. The hypothesis is that mathquill missed a character in the textarea for some reason (or failed to clear it) and didn't check again until blur. At that point it finds a character in the textarea and thinks it was a typed character. This then causes a dispatch-in-dispatch error because a completely unrelated dispatch was the cause of the blur.
I can't think of a time when we'd rather read a character out late compared to just ignoring the character. I think when it comes to keyboard input it's always safer to miss characters than make characters up. We should let this soak for a while to make sure this doesn't cause issues. I'm hoping to see a noticeable decrease in dispatch-in-dispatch errors over the …

stop trying to process keyboard actions on blur

---

src/services/focusBlur.js
src/services/textarea.js

Ensure that we assign role='math' to staticMath fields, and be sure to assign an initial ARIA label to new instances of MQ.mathFields if not focused immediately after creation.

Fix invisible static math on iOS with VoiceOver

---

src/commands/math/basicSymbols.js
src/controller.js
src/css/math.less
src/cursor.js
src/services/focusBlur.js
src/services/latex.js
test/demo.html
test/digit-grouping.html
test/unit/digit-grouping.test.js

`make server`
Then open http://localhost:9292/test/digit-grouping.html

add spaces between groups of digits

---

src/commands/math/commands.js
test/basic.html
test/unit/typing.test.js

cbrt is an alias for nthroot with the 3 prepopulated. to use, add to the list of autoCommands.
note: this makes it possible to paste in \cbrt (which is weird behavior, but matches what we do for nthroot), even though the serialized output is normalized to sqrt (also just like nthroot)

add support for cbrt plus tests

---

src/commands/math/commands.js
test/unit/typing.test.js

Currently we speak constructs such as cube roots like this: "Start 3 root, 12, end root." This PR alters the format to something less awkward: "Root index 3, start root, 5, end root."

Improve nthroot mathspeak

---

src/commands/math/basicSymbols.js
src/tree.js
test/unit/autoOperatorNames.test.js
test/unit/typing.test.js

Prevents us from using autoOperatorNames within simple subscripts. Sums and Ints use subscripts so we have tests to make sure those are still treated the same as before. The idea is that `a_{max}` should just be a simple variable rather than thinking `max` is a function call.

do not unItalicize autoOperatorNames when in simple subscript

---

src/commands/math/basicSymbols.js
test/unit/typing.test.js

When we serialize to LaTeX, commands like this need to have a space after them to separate them from following letters and numbers.

Fix serializing \sim and \approx.

---

script/test_server.js
test/unit.html

This PR does three things:
1.  Fixes a bug where the local test server was always reporting the local running port as 9292.
2.  Modifies the unit test page to synthesize test results in a way our internal testing framework expects.
3.  Removes the xunit reporting logic as we don't use it.

Add Jenkins support

---

src/css/math.less
test/unit/updown.test.js

We are going to want to heavily test exponent layouts before shipping this. There's a chance this fix breaks the layout of something else.
Before:
After:

fix layout of integrals within exponents

---

src/commands/math/basicSymbols.js
src/commands/math/commands.js
test/unit/paste.test.js

this is a hack to make pasting the √ symbol actually insert a sqrt command. This isn't ideal, but it's way better than what we have now. I think before we invest any more time into this single character we should consider how to make the pipe (|) automatically insert absolute value. We also will want the percent (%) to expand to '% of'. I've always just thought mathquill's ability to handle pasted latex magical until I started actually testing it. It's a lot more buggy that I previously thought.
KNOWN ISSUES:
1) pasting `√` does not put focus inside the sqrt symbol
2) pasting `√2` puts the 2 outside of the sqrt symbol.
The first issue seems like we could invest more time into this to fix it, but doesn't feel worth special casing. I think we'd want to address it by addressing ALL pasting …

allow pasting in the sqrt symbol

---

src/commands/math.js
src/commands/math/commands.js
test/unit/typing.test.js

This was written to specifically address an issue discovered with how MathQuill renders the overline command to screen readers.

Add ARIA/mathspeak info to math style commands

---

src/services/textarea.js

Windows screen readers along with VoiceOver on iOS will expose our hidden speech-friendly mathspeak representations of static math when the container's role is set to math.
The exact opposite is true for the Apple Mac, so if the user is on this platform, don't set the math role.

Don't use the ARIA math role for staticmath on the Mac

---

src/commands/math/commands.js
test/unit/SupSub.test.js
test/unit/autosubscript.test.js
test/unit/backspace.test.js
test/unit/latex.test.js
test/unit/publicapi.test.js
test/unit/typing.test.js

We always wrap roots and fractions, but rely on the LaTeX standard for things like x^23 being equivalent to x^{2}3.
This makes us more strict in LaTeX output, which will fix a bug with AIR's MathML parser. It makes some expressions a little uglier to copy and paste and read

Always wrap exponents and subscripts

---

Makefile

There are differences in the order that files get included when you compare the built file on linux and mac. I think the order that glob returns files differs between operating systems. We are now explicitly listing the files to avoid random differences. We only stumbled upon this because there is actually a bug that exists when mathquill is compiled on linux but doesn't exist when compiled on mac.  We are accepting the order that mac uses. There's no guarantee that this is the definite best order. Only time will tell.

harcode dependency order in Makefile

---

src/css/editable.less

This is an imperceptible difference in most cases (where it goes from 0px to 1px), and overrides larger border-radius if applied. Either useless or harmful depending on application. seeeya

get rid of bad border-radius rule

---

src/commands/math.js
src/css/math.less
src/tree.js

We want to start allowing empty lists, which are written as `[]`. The gray square makes this look wrong.
Ref: https://github.com/desmosinc/mathquill/pull/105 for when we did the same thing for empty parens.

Hide gray box in empty square brackets

---

Makefile

1) We cannot destroy the entire /build dir. Tup complains if that happens.
2) We cannot use hidden files. On linux tup complains about files that start with a period.

modify the makefile so that it can work within tup

---

src/services/textarea.js
test/unit.html

This expands an existing work-around to allow VoiceOver on iPad OS 13 and above to recognize static math content. iPads running iOS 13 spoof a Mac in their user-agent string, hence the expanded check. Logic adapted from a change we made to Albany in 2019.

Expand VoiceOver iOS work-around to account for spoofed Mac user agent

---

src/commands/math.js
test/unit/publicapi.test.js

For a long time, we had a hacky technique in our mathspeak logic which tried to separate our digits before and after the decimal point, in particular so that "123.456" would be read as "one hundred twenty three point four five six" on the Mac. The actual result was "123 .456" which somehow worked nearly everywhere except for iOS devices.
This PR replaces the earlier approach with a regex replace which splits out contiguous digits after the decimal point, so that "123.456" becomes "123.4 5 6" which will work everywhere.

Improve mathspeak post-decimal digit separation

---

Makefile

The build system has been using `sed -i` to do inline string replacement
in files, but the `-i` option to sed is not POSIX and its behavior
varies between GNU and BSD.
The build system attempted to detect which system you were on by
checking the behavior of a different flag (`-r`), but this detection no
longer works correctly on macOS Big Sur because it has added the `-r`
flag for compatibility with GNU (causing it to be incorrectly detected
as GNU).
Fix this by replacing `sed -i` with `perl -pi -e`. Perl is very widely
available, and its behavior here is more standard across systems.
Ref:
* https://stackoverflow.com/questions/3156178/how-do-i-use-perl-like-sed/37686753#37686753
* https://stackoverflow.com/questions/5694228/sed-in-place-flag-that-works-both-on-mac-bsd-and-linux/22247781#22 …

Fix Big Sur build

---

src/services/saneKeyboardEvents.util.js
test/unit/saneKeyboardEvents.test.js

Mathquill has a workaround for Linux that makes sure the appropriate element is focused on a paste event. This focus event bubbles in the usual way, so it may be observed outside mathquill.
This extra focus event started tickling a bug in the Desmos graphing calculator after upgrading from jQuery 2.x to 3.x. I suspect there may be a difference between these versions (possibly only in some browsers) in handling the case that the appropriate element already had focus.
Switch to only triggering this event if the appropriate element is not already focused to reduce the chance of triggering focus related application bugs.

Fix redundant focus event on paste

---

src/commands/math.js

It's apparently possible for static math LaTeX changes to become out of sync with its computed ARIA label and mathspeak content. This forces an update when LaTeX changes.

Force an ARIA update for static math when its LaTeX changes

---

src/commands/math.js
src/commands/math/basicSymbols.js
src/commands/math/commands.js
src/services/aria.js
test/unit/aria.test.js
test/unit/publicapi.test.js
test/unit/typing.test.js

- x^1 = "x to the first power"
- x^2 = "x squared"
- x^3 = "x cubed"
- Other values are spoken as "to the y power', e.g. x^10 is "x to the 10th power." The suffix "st", "nd", etc is only applied to exponents whose absolute value is less than 1000. After some testing, larger values began to clash with screen reader number parsing (especially with 7-digit strings that VoiceOver read aloud as a phone number).
- Anything else is spoken as before: "x, superscript, expression, baseline."
- - If both numerator and denominator are numeric integers and denominator is between 2 and 9, speaks a simplified form e.g. "1 half" or "3 quarters."
- Fractions will otherwise be spoken as before, e.g. "Start Fraction, numerator over denominator, End Fraction."
- If a whole number is followed by a simple …

Improve how common whole number combinations are spoken

---

src/commands/math.js
src/commands/math/basicSymbols.js
src/commands/math/commands.js
src/commands/text.js
src/tree.js
test/unit/typing.test.js

Improves how the mathspeak() method behaves for the content of text-related blocks
* For \text, implemented a mathspeak method which returns the block's content with no additional processing. Start and ending delimiters are also not announced unless the user navigates it in an interactive math field.
* For \mathrm blocks, also stop announcing start and end markers as above and treat individual characters as letters and not variables. This means, in particular, that we do not add quotes around individual letters or add whitespace between them. All other font style blocks behave as before.
* Added mathspeak capabilities to the \textcolor and \class commands as they were missing these methods.
See new tests for examples.

Improve Mathspeak for Text Blocks

---

src/commands/math.js
src/controller.js
src/css/mixins/display.less
src/publicapi.js
src/services/focusBlur.js
src/services/latex.js
src/services/textarea.js
test/unit/aria.test.js
test/unit/publicapi.test.js

The hack we've been using to try and hide the HTMLified output from screen readers while replacing it with a more verbal friendly mathspeak form has been reasonably effective, especially where standard editable math fields are concerned. The current technique has a couple of issues for static math:
1.  Screen reader users, regardless of platform, cannot review individual characters of a static math block, though in most cases they can hear the chunk inside the document. While navigating through a speechified version of math isn't the ideal experience, it would be an improvement over the current behavior so that a student could review any part of a math equation that needed repetition (e.g. because the formula is very complex, a long decimal is present, etc).
2. On some configurations …

Consolidate ARIA label update code and use hidden span for static math

---

src/publicapi.js
src/services/mouse.js
src/services/saneKeyboardEvents.util.js

jQuery 3.x has introduced a bunch of different focus bugs in the process of attempting to migrate to using native focus events in more cases, some of which remain unfixed in the latest version (3.6.0).
Examples:
* https://github.com/jquery/jquery/issues/4859
* https://github.com/jquery/jquery/issues/4856
* https://github.com/jquery/jquery/issues/4950
* https://github.com/jquery/jquery/issues/4867
Some unknown bug in this general class can make it so that Mathquill public api focus calls stop working because using jQuery to programatically trigger focus breaks.
Work around this by switching to triggering native focus events instead of jQuery focus events.

Use native focus events insted of jQuery focus events

---

src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/commands.ts
src/commands/text.ts
src/controller.ts
src/cursor.ts
src/services/aria.ts
src/services/keystroke.ts
src/services/mouse.ts
src/services/textarea.ts

Instead of appending the ARIA element to the document body and allow multiple Mathquill instances to share it, create the DOM when the textarea is instantiated, and make the ARIA span a child of same.

Scope ARIA element to mathquill instance

---

src/css/math.less

Add back relative positioning that was lost in the merge with upstream:
https://github.com/desmosinc/mathquill/pull/164/files#diff-79e9660ce59c4876801ff9682357e9e842311c5794d68c8ac77e3bc5c235de0dL419
Fixes https://github.com/desmosinc/mathquill/issues/170
Layout for these arrows is part of the visual test suite, which you can see by running `make test` at the mathquill repo route, and then doing `open test/visual.html`.
Before:
After:

Fix overarrow positioning

---

src/commands/math.ts
src/commands/math/basicSymbols.ts
src/commands/text.ts
src/css/math.less
src/publicapi.ts
src/services/focusBlur.ts
src/tree.ts
test/unit/quietEmptyDelimiters.test.js
test/unit/transparentDelimiters.test.js

Previously the Desmos fork purposefully removed the gray boxes for parens and square brackets which diverges from upstream's default. This change allows users to specify which delimiters are meant to be quiet (e.g. no gray background) instead.
The quietEmptyDelimiters value is expected to be a space-separated string of brackets-- (, ), [, ], {, }, langle, or rangle.
For example, to restore the Desmos style:
```
var el = $('<span></span>');
var mq = MQ.MathField(el[0]);
mq.config({
quietEmptyDelimiters: '( ['
});
```
Related PR into Knox: https://github.com/desmosinc/knox/pull/12104

Add quietEmptyDelimiters option

---

src/commands/math/basicSymbols.ts
src/publicapi.ts
src/tree.ts
test/unit/autoOperatorNames.test.js
test/unit/typing.test.js

When set, causes Mathquill to provide no transformations to auto commands, automatically parenthesized functions, and auto operator names if their parent is a simple subscript. Disabled by default.
Related PR into Knox: https://github.com/desmosinc/knox/pull/12110

Add "disableAutoSubstitutionInSubscripts" option

---

Makefile

Currently, running `make` will frequently leave `package-lock.json` modified because it runs `npm install`, which is allowed to upgrade dependencies according to the rules in `package.json`.
`npm ci` installs exactly what's specified in `package-lock.json` and never modifies it.

Use npm ci instead of npm install when building

---

src/commands/math.ts
src/commands/math/basicSymbols.ts
src/commands/text.ts
src/services/latex.ts
src/shared_types.d.ts
src/tree.ts

`parser()` methods can return an `MQNode` or a (possibly empty) `Fragment`. Previously, our annotations suggested that `parser()` methods could only return MQNode, but the confusion about this forced a lot of casting. Annotate this correctly and remove ParserAny casts.

Clarify parser types

---

src/services/keystroke.ts
src/tree.ts
src/utils.ts

This can improve type narrowing after the pray call. This PR only uses this to ensure that abstract methods that should never be called can't return, but I suspect we'll find other places that this makes pray more useful.
Ref: https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/#assertion-functions

Give pray an asserts signature

---

src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/commands/text.ts
src/cursor.ts
src/publicapi.ts
src/services/keystroke.ts
src/services/latex.ts
src/services/scrollHoriz.ts
src/tree.ts
test/unit/tree.test.js

MathQuill has a few data structures that can point to a doubly-linked list of sibling nodes. `MQNode` does this to hold onto the children of the node, and `Fragment` does this to represent spans of sibling nodes. Both `MQNode` and `Fragment` hold onto these lists using an `ends` property with references to the left and right end of the list.
In general, these lists may be empty, which is represented by setting both ends to `0` instead of an `MQNode`. But child classes (e.g. specific kinds of `MQNode` like `SupSub`, or specific kinds of `Fragment` like `Selection`) may want to enforce that ends are not empty, or that they are a more specific subtype of `MQNode`.
These constraints on child classes weren't represented in the type system, which was forcing a lot of casts.
This PR:
1. Makes …

Improve typing of node and fragment ends

---

src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/cursor.ts
src/domFragment.ts
src/publicapi.ts
src/services/focusBlur.ts
src/shared_types.d.ts
src/tree.ts

Implement `hasClass`, `addClass`, `removeClass`, and `toggleClass` on `DOMFragment` and use these instead of jQuery.
Implemented in terms of `classList`. I think it'd be reasonably easy to have a fallback using string operations on `className`, but I'd rather defer that to a later pass. (Added this as an optional cleanup in our tracking document).

Remove jquery class manipulation

---

src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/commands/text.ts
src/cursor.ts
src/domFragment.ts
src/publicapi.ts
src/services/latex.ts
src/services/textarea.ts

`insertBefore` and `insertAfter` now take a whole `DOMFragment` as an argument instead of a single `Node`. Removes many runtime asserts that were added in c85ce0c.
The asserts were useful while doing the translation to ensure we didn't differ in behavior in any cases where `insert{Before,After}` were called with multi-element jQuery collections, but now that that translation is complete, they aren't needed anymore.
Similarly, lifts the requirement in `.replaceWith()` that `this` is a single `Node` collection.
As a follow-on, refines other `.one()` assertions to either `.oneElement()` or `.oneText()`. `.one()` now has no external callers, and has been renamed to `.oneNode()`.

Make insertBefore and insertAfter more flexible

---

src/commands/math.ts
src/commands/text.ts
src/cursor.ts
src/publicapi.ts
src/services/mouse.ts
src/tree.ts

The browser implicitly privileges client coordinates by providing a `getBoundingClientRect` method but not a `getBoundingPageRect` method. If we work consistently in terms of client coordinates instead of page coordinates, we can avoid having to query the page scroll position all the time.
There's one place that page coordinates can't be removed: the arguments to `dropEmbedded` because this is part of the public API. What a pain.

Consistently use client coordinates instead of page coordinates

---

src/css/editable.less

Looks like this first landed here https://github.com/desmosinc/mathquill/commit/dcb831f7d93a8ca933532d14b8f995bf7fd42acd
I can't find any evidence that any browser supports an `aria-hidden` CSS property (as opposed to the standard element attribute). When an element has this CSS property, browser dev tools show me an "unknown property name" warning.

Remove unsupported aria-hidden CSS property

---

Makefile
src/dom.ts
src/domFragment.ts
test/support/assert.ts
test/unit.html
test/unit/dom.test.ts
test/unit/domFragment.test.ts

`DOMFragment` now has 100% line coverage _except for_ the `.toJQ()` method and the `jQToDOMFragment` method. I didn't bother writing tests for these since they will go away by the end of this project.
TODO

Unit test DOMFragment

---

src/cursor.ts
src/services/aria.ts
src/services/textarea.ts

This fixes a problem where Google Chrome and Mac VoiceOver weren't reporting updates to the ARIA live region as the user typed. The previous solution had two issues:
1.  Tried to guess when to insert the ARIA element (tricky because Mathquill's DOM undergoes some permutations when being initialized, and it was possible for the ARIA element to parent itself to a detached element). Not initially noticed because tests worked in everything except Mac and Chrome, and the ARIA fragment is visually hidden. Now, we wait until the ARIA element is needed (when alert() is called), and at that point try to attach the fragment. If that fails, we will try again the next time an alert is called.
2. Even when the element was attached to something in the DOM, Chrome was always one ARIA alert behind. …

Stop using JQuery for ARIA alert element

---

src/commands/math.ts
src/commands/math/commands.ts
src/css/textarea.less
src/cursor.ts
src/dom.ts
src/publicapi.ts
src/services/textarea.ts
test/unit/aria.test.js
test/unit/dom.test.ts
test/unit/latex.test.js
test/unit/publicapi.test.js

> Adding aria-hidden="true" to an element removes that element and all of its children from the accessibility tree.
([source](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden))
We currently set `aria-hidden` at a lot of internal nodes of the math DOM, but it should only be necessary to set it on root blocks. Switch to doing that.
There's one wrinkle here, which is the `MathFieldNode` which allows nesting an editable math field somewhere inside a static math display. In that case, in order to have the `textarea` of the nested `MathFieldNode` and the associated aria-live region visible in the accessibility tree, we need to remove `aria-hidden` from the root block of the static math field, and "push it down" to all the other siblings that are not parents …

Reorganize aria hidden

---

src/commands/math.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/commands/text.ts
src/publicapi.ts
src/services/textarea.ts
src/shared_types.d.ts
src/tree.ts
test/unit/publicapi.test.js

For `MathQuill.getInterface(2)`:
- Return an HTMLElement instead of a jq collection from revert()
- Remove substituteKeyboardEvents() configuration option

Remove JQuery from version 2 of the public MQ interface 

---

src/services/aria.ts

We began seeing "t.prepend is not a function" inside the scientific calculator in Bugsnag. I was not able to reproduce the issue locally so am adding a few additional checks that we can call prepend when generating an ARIA alert.
Related Knox PR: https://github.com/desmosinc/knox/pull/12151

Add a more paranoid check that it is safe to prepend ARIA alert element

---

src/services/textarea.ts
src/shared_types.d.ts

Replace only two usages of jQuery attr method with the native DOM `setAttribute` method.

Replace only two usages of jQuery attr method

---

src/commands/math/commands.ts
src/shared_types.d.ts

Replace only three usages of jQuery `.css` method with native DOM `style` property assignments.

Replace only three usages of jQuery .css method

---

Makefile
src/animate.ts
src/services/scrollHoriz.ts
src/shared_types.d.ts

We are only using `animate` to scroll math horizontally depending on your cursor position in case of overflow.
I made a new `animation` library function to replace the jQuery method. See the doc comment for a description. It's a lot lower level than the `jQuery` version, which I think is fine because it only has two callers.
To see this in action, run `make test` and then open `test/visual.html`. There is a section labeled "Horizontal overflow". Type enough into the box in that section to make it overflow, and then notice that if you remove focus from the box, there is an animated scroll.

Replace jQuery animate with a new animate library function

---

benchmark/render.html

Our LaTeX rendering benchmark lets you control the maximum size of expressions that will be produced, but when it hits that cap, it can pass in too few parameters to a function for the required arity. This problem appears to be common, and when it happens, we end up with the string "undefined" inserted into the test LaTeX.
To address this, switch to iterative deepening to control max length, and never pass incorrect arity to the subexpression generators.
Before/After images generated using `/benchmark/render.html?seed=0f2c963a&expressions=10&samples=1`.
Note the many occurrences of "undefined" in "Before".
After this change, it looks like the benchmark tends to produce smaller expressions, but it does also still produce some pretty large ones. Several of the examples that are "below the …

Fix inserting undefined into benchmark latex

---

Makefile
src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/commands/text.ts
src/controller.ts
src/mathquill.d.ts
src/outro.js
src/publicapi.ts
src/services/keystroke.ts
src/services/latex.ts
src/services/parser.util.ts
src/shared_types.d.ts
test/tsconfig.public-types-test.json

This PR adds a standalone set of public types for the MathQuill API, and updates the internal types to be written in terms of the public ones to the extent that it's feasible to do so.
Because of the dynamic `getInterface()` system, it is difficult to have the implementation fully type checked against the public types without duplicating (or drastically restructuring) a lot of code.  Instead, I chose to have `getInterface()` checked against version 3, using a few casts to deal with the places where older interface versions conflict.

Add standlone public type definitions

---

src/services/saneKeyboardEvents.util.ts
test/unit/saneKeyboardEvents.test.js

MathQuill uses some non-standard key names internally like `'Del'` for `'Delete'`, `'Spacebar'` for `' '`, etc.
We broke using some of these keys when we switched to relying on `evt.key` when it exists in preference to `evt.which`.

Fix Delete key and other keys with names that MQ remaps

---

src/tree.ts
test/unit/typing.test.js

Examples:
* A LatexCommandInput with a `_replacedFragment`
* In some cases, embed nodes
* LatexFragment, which is produced by inputs like `½`

Fix Fragments containing a single MQNode represented by multiple DOM nodes

---

src/domFragment.ts
src/tree.ts
test/unit/domFragment.test.ts

This is no longer needed now that `Fragment` checks whether its ends are equal before attempting to join their DOMFragments.

Disallow joining overlapping DOMFragments

---

src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/commands.ts
src/commands/text.ts
src/cursor.ts
src/dom.ts
src/domFragment.ts
src/publicapi.ts
src/services/latex.ts
src/tree.ts
test/unit/dom.test.ts
test/unit/domFragment.test.ts

A DOMFragment can be invalidated if one of its ends is moved to no longer be a sibling of its other end. In practice, we see this when one end of (the children of) a math block is selected (which wraps it in a selection span) and the other end is not selected.
Make it clearer that we are not working with invalidated DOMFragments by not storing them. Instead, store direct references to DOM nodes and construct DOMFragments in the `.domFrag()` getters.
This doesn't make the selection problem impossible, but it does mean we'll notice it immediately in the validation of the `DOMFragment` constructor, instead of possibly operating on a DOMFragment that was valid when it was created but has become invalid.

Avoid storing DOMFragment

---

src/cursor.ts
src/services/focusBlur.ts

`resetToEnd` caused a bug when called from `renderLatexMathEfficiently` that was fixed in https://github.com/desmosinc/mathquill/pull/226
I think this method has a fundamental behavior problem in that it adjusts the cursor model but does not update the corresponding DOM. Replace it with insAtRigthEnd.
Ref:
* PR where `resetToEnd` was added: https://github.com/desmosinc/mathquill/pull/226

Remove remaining callsite for resetToEnd

---

src/services/latex.ts

Previously, if you set the exact same latex as what was currently set, the cursor would not be moved to the end, but in all other cases, it would be. I think this is confusing and could allow bugs in that special case that don't exist in other cases.
Now, pull out logic for moving the cursor and for checking whether the latex is exactly the same into the `renderLatexMath` method to clarify that it should be the same whether we run `renderLatexMathEfficiently` or `renderLatexMathFromScratch`.
Also rename `renderLatexMathEfficiently` to `updateLatexMathEfficiently`.
Note: I have verified that this benchmark does not significantly impact `benchmark/update.html`

Clarify cursor update in renderLatexMath

---

src/cursor.ts
src/services/focusBlur.ts

Revert https://github.com/desmosinc/mathquill/pull/227
That was a speculative improvement, but our error monitoring suggests that it's causing problems in practice by sometimes creating a situation where the cursor parent is undefined.

Revert "Remove remaining callsite for resetToEnd"

---

src/commands/math/commands.ts

Instead of setting the css color to the argument passed to
\textcolor, the code was setting it to the word "color".
Unquote it a bit to give working behavior. The typo came
from the jquery code which passed everything as a single
string, versus the new style which uses javascript properties,
and thus has one less layer of quoting.

Fix \textcolor quoting issue

---

test/visual.html

In 51a75093dac047399e64a0d06a68c937c0df5a3e we accidentally started dispatching the `CTRL-A` keydown to the first textarea on the page instead of to the `#selection-tests` text field.
I wasn't previously familiar with the use of the second arg to the `$()` function, but it's a "context" in which selector will be applied. So I think
```js
$('textarea', this)
```
is roughly equivalent to
```js
$(this).find('textarea')
```
Ref:
* https://api.jquery.com/jQuery/#jQuery-selector-context
Reported in https://github.com/desmosinc/mathquill/issues/236

Fix selection in test/visual.html

---

src/commands/math.ts

In change 71df65d the name "delegateMouseEvents" changed from
meaning "add" to "remove" (remove previously had no name). This
was partially fixed in eb510ccf but this call site should have
been "add" instead of "remove".
Thanks for finding the exact commit!
I don't think this fixes the container click bug bisected to the same commit

Fix clicking on `\MathQuillMathField`

---

src/services/keystroke.ts
test/unit/typing.test.js

Cursor.show has a special case for where to place the cursor DOM when there is something to the right of the cursor and there is a selection:
https://github.com/desmosinc/mathquill/blob/9606bd8a7a931a8902346793083f4c1093f49d01/src/cursor.ts#L80-L81
When escaping to the left out of a block with an active selection, the selection was previously not being cleared, which was causing the cursor DOM to get put in a place that was related to the previous selection instead of to where MQ's model of the cursor says it should be.

Fix Shift-Tab and Shift-Escape with a selection

---

src/publicapi.ts
test/unit/publicapi.test.js
test/visual.html

`substituteKeyboardEvents` is only supported in interface versions <=2, so make a MQ with interface version 2 to use for these tests.
Makes it an error to pass `substituteKeyboardEvents` in interface version >=3.

Fix visual test substituteKeyboardEvents section.

---

src/services/mouse.ts

`DOMFragment.prepend` asserts that the dom fragment has exactly one element. Prepending to an empty fragment doesn't really make sense.

Don't attempt to prepend to an empty DOMFragment.

---

test/visual.html

Update visual test "Touch taps/clicks/mousedown to drag should work anywhere in the blue box" to trigger native DOM events instead of jQuery events.
MathQuill no longer listens for jQuery triggered events. To get MQ to respond to triggered events, it is now necessary to use native DOM events.
Fixes https://github.com/desmosinc/mathquill/issues/236

Fix visual test that redirects mousedowns from a larger target area

---

docs/Api_Methods.md
src/commands/math.ts
src/commands/math/LatexCommandInput.ts
src/commands/math/commands.ts
src/commands/text.ts
src/cursor.ts
src/publicapi.ts
src/services/latex.ts
src/shared_types.d.ts
src/tree.ts
test/unit/latex.test.js

Adds a `.selection()` method to get the current selection out of the mathquill instance. Will return something like:
```
{
latex: '12345'
startIndex: 2,
endIndex: 3
}
```

export selection

---

src/commands/math.ts
src/commands/math/basicSymbols.ts
src/mathquill.d.ts
src/publicapi.ts
test/unit/typing.test.js

There has long been a discrepancy in Mathquill for how a tilde is handled. When typing from the keyboard, we bound the key to write a \sim symbol, but let raw tilde characters through if Latex was externally set.
This PR:
- Sets the tilde symbol to belong to the list of LaTeX commands (rather than character commands) so that Mathquill properly transforms the externally set tilde symbol either into a standard tilde (which appears as a nonbreaking space) or, if the "interpretTildeAsSim" option is set, a \sim operator.
Note: tilde characters input directly from the keyboard will continue to be transformed into \sim operators as we have always done.
Related Knox PR: https://github.com/desmosinc/knox/pull/12340

Update tilde behavior

---

src/commands/math/commands.ts
src/services/mouse.ts
test/unit/latex.test.js

A Token represents a region in typeset math that is designed to be externally styled and which delegates mousedown events to external handlers.
LaTeX syntax: `\token{id}`.
Token is designed for similar use cases as EmbedNode. Differences:
* Mousedown events on a Token are not handled by MathQuill (they are expected to be handled externally).
* The API for Tokens is simpler: they don't require registering handlers with MathQuill.
* The current syntax for embed (`\embed{name}[id]`) gets the order of optional and required arguments backwards compared to normal LaTeX syntax. The syntax of Token is simpler and more in line with LaTeX.

Add \token symbol

---

src/commands/math/commands.ts
src/domFragment.ts
test/unit/aria.test.js

If a token element includes children that specify aria-labels for the inner elements, use a concatenation of those values as the token's mathspeak value. If none exist, return a more unique identifier of "token xxx", where xxx is the parsed id.

Better mathspeak values for tokens

---

src/commands/math/basicSymbols.ts

Allows the auto-command "cross" to produce `\times` instead of (invalid) `\cross`.

Support typing 'cross' for '\times'

---

src/mathquill.d.ts
src/publicapi.ts
src/services/aria.ts

next up: in the calculators adding an "logAria" URL parameter that will log everything the screen reader will say, which will be great for demos and for debugging without the screen reader on.

Add support for logging aria alerts

---

src/services/mouse.ts

There is a bug in android where multiple mousedown events are being fired so we don't want this being cleared after the first one. We will set this callback up once and just make sure it's returning the correct thing always.
There is only 1 use of this that I can find and it's in the exact spot that we want to leave it around. We couldn't find any uses of it in classroom.
Corresponding knox pr: https://github.com/desmosinc/knox/pull/14864

do not unset the ignoreNextMousedown option

---

src/services/mouse.ts

This reverts commit f72216d5cb725fcfd04b008f79bff578fad2444c.
There may or may not be an issue with this. It was built specifically to cooperate with a change in knox. We've reverted that change so we should revert this just to be safe.

Revert "do not unset the ignoreNextMousedown option"

---

src/commands/math/advancedSymbols.ts
src/commands/math/basicSymbols.ts
test/unit/typing.test.js

E.g. you can type/paste "θ" and get "\theta" instead of the raw unicode θ. Inside Desmos, this means you can paste `r=\sin\left(θ\right)` and get a valid equation instead of "Sorry I don't understand the 'θ' symbol."
There was already *some* support for this, e.g. `→`, `π`, `≤`, but it was missing for all Greek letters and many advanced symbols. My plan was to just do the Greek letters, but I got carried away.
For each added unicode support, I verified:
- (by grep) The unicode appears only once in the source (e.g. `LatexCmds['∇']` only appears once)
- This ensures that there's no `advancedSymbols` definition overwriting a `basicSymbols` definition.
- (by pasting into a mathquill field) The mathquill glyph for the corresponding command roughly matches my local glyph (from font Julia Mono) …

Support typing Unicode for all symbols

---

src/commands/math/commands.ts
test/unit/aria.test.js
test/unit/typing.test.js
test/unit/updown.test.js

Mathquill supports:
- Binomial coefficient `\binom{}{}` analogous to Fraction `\frac{}{}`
- `\choose` almost analogous to typing `/` to create a fraction, but more analogous to `\over` (which also works in Mathquill)
This PR makes three changes:
- Fixes bug where typing "choose" gave a TypeError (prototype was called without `.call`)
- Allows Up and Down keys to navigate a binomial.
- Adds better aria support.
For all three changes, the tests are copy-pasted from the fraction tests with minor changes.

Fix \binom and \choose

---

src/services/focusBlur.ts

Alt-tab to a different window or Ctrl+Tab to a different tab, then switch back. Current behavior with `resetCursorOnBlur: true` (which Desmos has) is to move the cursor to the end of the math field. Now, leave the cursor where it is.
In Desmos: `resetCursorOnBlur` is used to ensure there's not a different cursor state for each mq field in the expressions list. When the user selects a new field (or clicks away from all fields), the cursor on the old one resets to the end of the field.
Switching to a different tab/window doesn't change which field is selected, so it's okay to leave the cursor where it is.
I don't think this PR can be tested with mathquill's testing framework. focusBlur.test.js handles regular blurs but not window blurs.

Dont reset cursor on window blur

---

docs/Config.md
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/mathquill.d.ts
src/publicapi.ts
test/unit/infixOperatorNames.test.js

Main change is adding the option `infixOperatorNames`, used for something like `for`, where `(t,t)for1/` should give `(t,t)for\frac{1}{ }` instead of `\frac{(t,t)for 1}{ }`.
Also some minor refactors (first two commits) of code that confused me while looking for where to make this change.
Knox PR https://github.com/desmosinc/knox/pull/15798.

Add infixOperatorNames option

---

src/commands/math/commands.ts
test/unit/backspace.test.js

Setup: cursor immediately before a square root, e.g. at the start of a field with latex `\sqrt{x}`
Before: pressing "delete" (delete-to-the-right) would move the cursor to the right.
After: pressing "delete" (delete-to-the-right) deletes the square root and keeps the content within.
This matches the behavior of pressing "delete" when the cursor is at the far-right of the radix/index/degree of an nthroot.
It just does the same as typing "Right" then "Backspace" (delete-to-the-left).
I also put some tests for "Delete" since there were previously only tests for "Backspace," added in https://github.com/mathquill/mathquill/pull/453/commits/4a8779f76f9e6c26fc8bb389e9aa5a8f50efe1b7.

Delete sqrt with 'delete' before it, and add 'delete' tests

---

docs/Config.md
src/commands/math/commands.ts
src/mathquill.d.ts
src/publicapi.ts
test/unit/typing.test.js

Adds an option to disable range matching like (a,b] or [a,b). Updated config type, added test, and updated config.md. Hope I didn't miss anything, not super familiar with mq codebase. Test is outside of restrictMismatchedBrackets suite because it uses a different value for the option.

Add "none" option for restrictMismatchedBrackets

---

test/unit/typing.test.js

Turns out a `test()` nested inside a `test()` just doesn't run. Nest using `suite()` only.

Fix restrictMismatchedBrackets "none" test.

---

docs/Config.md
src/commands/math.ts
src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/mathquill.d.ts
src/publicapi.ts
test/unit/infixOperatorNames.test.js

Adds an option `prefixOperatorNames` to specify which names behave as prefixes. In Desmos, this is used for "ln," "log," and the trig functions such as "sin." A minus sign (`-`) after any such name is treated as "negative" instead. This affects spacing (there's less space after a "negative" than after a minus sign) and mathspeak / aria labels. For example, `\sin -1` is read as "sine negative 1" instead of "sine minus 1."
Also, all of the existing `infixOperatorNames` (such as "for" in Desmos) have the same treatment, so `(t,t) for -1 < t < 1` contains "for negative 1 less than" instead of "for minus 1 less than."
Before/after comparing spacing (less space after "negative")

Recognize "-" as "negative" after certain operator names

---

src/commands/math/basicSymbols.ts
test/unit/infixOperatorNames.test.js

This PR makes PlusMinus behave as binary after close-brackets.
Before PR:
After PR:
In the latex `\left(x\right)+`, the call `nodeEndsBinaryOperator` would be applied when `node` is the "+". But then `nodeL = node[L]` gives the whole `Bracket` node represented by `\left(x\right)`, whose ctrlSeq is `\left(` (and has the `x\right)` as children).

Make PlusMinus binary after close-bracket

---

src/services/saneKeyboardEvents.util.ts

Original work from @RyanMelenaNoesis plus a run through prettier from myself.

Fix issue typing UNICODE characters from ArithmeType keyboard in modern Chromebooks

---

src/commands/math/basicSymbols.ts
test/unit/digit-grouping.test.js

Fixes incorrect spacing in `[-10,-...9]`. The old incorrect behavior treated everything before the `...` as a digit, so it put a thin space between the `1` and the `0`.
The spacing code needs to space-out the ellipsis `...` and backtracks to space out whatever's before the ellipsis. A typical scenario here is like `[1234...5678]`. It backtracks to space out left=`1`, right=`4`, then it continues on to space out left=`5`, right=`8`.
The bug comes from assuming that whatever's before the ellipsis is a digit. Just before you write the 9, the latex looks like `[-10,-...10]`. The backtrack is to left=`.`, right=`-`. This is incorrect and it ends up spacing `-10,-` as if that was a single number `x10yz` where x,y,z are digits. Then the space goes between 1 and 0.

Fix edge case of non-digit before ellipsis

---

src/commands/math/commands.ts
src/css/math.less
src/dom.ts

When traversing the DOM to render the labels into canvas we cannot find/measure the pseudo elements. We need real DOM. So this puts real DOM in the page for those elements so that we can copy them to canvas. Also fixes a bug where the color of the overarrow line / arc was hard coded to black in some cases.

use real dom for overarrow isntead of :before and :after pseudo dom

---

src/commands/math/basicSymbols.ts

Adds the following symbols to "basic symbols" - 
* Not congruent
* Not similar

Adds Symbols to Basic Symbols for Classroom Geometry

---

src/commands/math/advancedSymbols.ts
src/commands/math/basicSymbols.ts

Moves the following symbols from advanced to basic: 
- bigcirc 
- angle
- degree
- triangle
- cong
- measuredangle
- parallelogram
And **adds** the following symbols to basic:
- not congruent
- not similar

Classroom Symbols For Geometry

---

.husky/pre-commit
package-lock.json
package.json
src/publicapi.ts

Upgrades (most) dependencies to address deprecation warnings and security vulnerabilities.
Currently main has: `22 vulnerabilities (7 moderate, 12 high, 3 critical)`, this branch has 0.
I left prettify and uglifyjs alone since both of those looked like potentially thornier upgrades (prettier mainly b/c it would introduce code changes, may do that in a separate PR).

Upgrade dependencies

---

package.json

This command is no longer necessary on v9.0, and I forgot to remove it from the previous PR.

Remove deprecated husky install command

---

.github/workflows/mathquill-pr-linting.yml

Updates the github actions runners to v4, and proactively adds node 22 to the matrix of node runners we support.

Update github actions runners to v4

---

docs/Config.md
src/mathquill.d.ts
src/publicapi.ts
src/services/focusBlur.ts
src/services/mouse.ts
src/services/textarea.ts
test/basic.html
test/demo.html
test/unit/aria.test.js
test/unit/focusBlur.test.js

Note: as Jared noticed, this isn't backwards compatible if people are using substituteTextareas for StaticMath and don't pay attention to the tabbable property.

Proof of concept: another approach to making static math focusable

---

src/commands/math.ts
src/commands/text.ts
src/mathquill.d.ts

Follow on to https://github.com/desmosinc/mathquill/pull/305 which gave more specific types to some chainable methods like `.blur()`.
This way reduces a bit of redundancy.

Type chainable methods generically

---

.github/workflows/mathquill-pr-linting.yml

Drop node 16 and 18 from CI, keeping 20 and 22. I was finding it a little distracting to see this many similar CI jobs.

Drop older node versions from CI

---

src/services/focusBlur.ts

Reaching into the "selection.clear" event doesn't also delete the "selection" object, and it seems like the system expects selection to be truly deleted. 
The symptom was that MQ.getSelection() was returning whatever had been _previously_ selected, even if nothing was currently selected.

truly clear selection

---

src/services/textarea.ts
test/unit/aria.test.js

Useful so that math embedded in prose is clearer to read with a screen reader. For example, without this change, any instance of static math is preceded with "multi-line edit" followed by the mathspeak representation of the content.

Aria-hide non-tabbable textarea element for static math

---

docs/Config.md
src/commands/math/basicSymbols.ts
src/mathquill.d.ts
src/publicapi.ts
src/tree.ts
test/unit/autoOperatorNames.test.js

Pass the option `disableAutoSubstitutionInSubscripts: { except: "log" }` to allow `log_pi` to type `\log_{\pi}` but keep `x_pi` typing `x_{pi}`.
Also, documents the config option since it was undocumented before.

Allow substitution in subscripts after log, based on config

---

src/controller.ts
src/services/textarea.ts
test/unit/aria.test.js

This PR makes two subtle changes to focusable static math:
1.  Use the "aria-labelledby" attribute to link the focusable static math textarea element with its accompanying mathspeak region.
2. Explicitly remove the empty aria-label attribute for focusable static math because the attribute is now redundant. I believe this also solves a problem observed only in JAWS for Windows where focusable static math wasn't readable in the Desmos calculators where such fields are used (e.g. evaluations and computed table cells).

Link focusable static math textarea with mathspeak region through ARIA

---

src/controller.ts
src/services/aria.ts
src/services/focusBlur.ts
src/services/textarea.ts
test/unit/aria.test.js

First, adds the aria-hidden attribute to any focusable mQ's mathspeak region so that screen readers don't double-report the content, e.g. when the field is used as a table column header.
Second, empties the content of the math field's internal ARIA alert element when the field loses focus. Helps with the first problem above, but is something we should have been doing anyway.

More mathspeak and ARIA clean-up

---

docs/Config.md

Add documentation for speech alternatives in autoOperatorNames. This is not implemented in upstream MathQuill as far as I can tell, so am submitting the PR here instead of there.

Add documentation for speech alternatives

---

src/mathquill.d.ts
src/publicapi.ts
src/services/mouse.ts
test/unit/focusBlur.test.js

This makes two changes that will be helpful for static maths in the calculator:
(1) adds a "select" method to StaticMath, so that we don't need to rely on initial focus as the only way to select content
(2) fixes a bug where mousedown on a static math would -- just the first time -- fire off a focus event, before anything was selected.
Repro for this (very subtle):
(1) open https://www.desmos.com/scientific
(2) type sqrt(2)
(3) click on the evaluation on the right (note that the expression would deselect)
(4) click back into the left side to re-focus the expression
(5) click on the evaluation on the right again (note the expression doesn't deselect the second time)

Small tweak to focus behavior

---

docs/Api_Methods.md
docs/Config.md
src/controller.ts
src/mathquill.d.ts
src/publicapi.ts
src/services/textarea.ts
test/basic.html
test/demo.html
test/unit/aria.test.js
test/unit/focusBlur.test.js

this dynamically sets tabbability, and mutates tabbability inside of mathquill, removing the "tabbable" argument to substituteTextarea.
small optimization: this is a no-op if it's set the previous value.
tiny related optimization for setAriaLabel: that method now likewise returns early if the update will be a no-op

add "tabindex" property and methods

---

docs/Api_Methods.md
src/mathquill.d.ts
src/publicapi.ts
src/services/latex.ts
test/unit/latex.test.js

This adds the ability to set the mathquill selection. We already had the ability to read it. In principle there was enough information in the the `{latex, startIndex, and endIndex}` to be able to restore the selection but in practice it's much more useful to have a path to a node and then a number of times to either simulate a `shift-left` or `shift-right`. There doesn't appear to be a way in mathquill to simple set the selection between two nodes. The way you must do it is based on finding a node and then growing the selection in a direction. Saving the instructions to find the the anchor and then optionally growing the selection with a certain number of left or rights makes setting the selection pretty straightforward.
Because the way we are indexing into the MQ tree is with a series of …

Allow setting selection

---

docs/Api_Methods.md
src/controller.ts
src/mathquill.d.ts
src/publicapi.ts
src/services/mouse.ts
test/unit/publicapi.test.js

Returns `true` if the user is currently selecting text with the mouse, `false` otherwise. This can be useful for preventing certain actions (like setting the cursor position) while the user is actively dragging to select text. The method tracks mouse selection from the moment the user presses the mouse button down to start selecting until they release it or the selection is cancelled due to an edit operation.
```javascript
if (!mathField.isUserSelecting()) {
// Safe to programmatically change cursor position
mathField.moveToLeftEnd();
}
```

add mq.isUserSelecting() method to check if a mouse selection is active

---

src/commands/math/basicSymbols.ts
src/commands/math/commands.ts
src/services/aria.ts
test/unit/publicapi.test.js
test/unit/typing.test.js

Mathquill had separate `SubscriptCommand` and `SuperscriptCommand` node classes, which were subclasses of `SupSub`. 
Before this PR, it was possible to create a `SuperscriptCommand` that only contained a subscript with the following steps:
1. Create a superscript like `x^2`
2. Add a subscript, `x_1^2`
3. Remove the superscript, `x_1`.
(The reverse is possible as well; you could make `x^2` be a `SubscriptCommand` by switching superscript and subscript in the steps).
This caused an issue when you typed `)` after the resulting `x_1` because it duplicated the subscript to the superscript, giving `x_1^1`. (presumably in `finalizeTree`). A simple fix for that would be to do change the prototype to a `SubscriptCommand`, but instead this PR removes the `SuperscriptCommand` and `SubscriptCommand` …

Prefer logic on the SupSub node rather than separate logic on SubscriptCommand and SuperscriptCommand

---

src/commands/math/commands.ts
test/unit/typing.test.js

A user reported typing √ having funny behavior (Option+V on mac -- might require opening Grapher first). This PR fixes that.
There's a few other [documented unicode related to Grapher](<https://support.apple.com/guide/grapher/keyboard-shortcuts-gcalc09ef510/mac>) that mathquill already supports (∑, ∫, ∏). This PR adds tests  for those too.

Support typing √ directly
