desmosinc/mathquill

- src/commands/math.js
- src/commands/math/basicSymbols.js
- src/css/math.less
fixes weird chrome display bug
> simplify .mq-f rules

- src/css/editable.less
breaks sums in FF. discussed here:
https://github.com/mathquill/mathquill/commit/32a48e4
> remove bad white-space rule

- CHANGELOG.md
- README.md
- package.json
- src/css/main.less
- src/css/math.less
- src/cursor.js
- src/intro.js
- test/unit/publicapi.test.js
just ran a `git merge dev`
I'm worried that we have some duplicate commits. In particular:
* `update squiggle html output`
* `check that we have a select method`
> Dev dcg merge

- src/commands/math.js
- src/commands/math/basicSymbols.js
- src/css/textarea.less
- test/unit/publicapi.test.js
also pulls in one change to mathquill/mathquill. let me know if those should be separate PRs?
> Fix chrome display bug

- src/commands/math/basicSymbols.js
Version of https://github.com/mathquill/mathquill/pull/317 target toward dev.
> Bubble a "reflow" when an inequality changes to/from strict.

- src/commands/math/basicSymbols.js
- src/commands/math/commands.js
- src/css/math.less
- src/css/mixins/css3.less
- src/css/textarea.less
- test/unit/publicapi.test.js
- test/unit/typing.test.js
- test/visual.html
Cherry picking:
https://github.com/mathquill/mathquill/pull/602
https://github.com/mathquill/mathquill/pull/603
https://github.com/mathquill/mathquill/pull/604
And this single commit: https://github.com/mathquill/mathquill/commit/bea3ed6f202529aa9950236bcea894b513c94fd0
The former three to get awesome integral behavior. The last one to get the transform mixin that is relied on in rendering operators.
Killer stuff @laughinghan. integrals are so beautiful after this.
> Cherry pick integrals

- src/commands/math/commands.js
Wraps "ans" up in a span with a .mq-ans class
> add \\ans LatexCmd

- src/commands/math/commands.js
fixes https://github.com/mathquill/mathquill/issues/632
Fix suggested by @laughinghan. he'll get the same fix in with tests in mathquill
> don't punt early with selection

- src/services/saneKeyboardEvents.util.js
- test/unit/saneKeyboardEvents.test.js
He put a PR up here: https://github.com/desmosinc/mathquill/pull/35 but my PR had already been merged. Putting up a separate one to make sure we end up in the correct state after the merge.
> Revert my fix for copy and use Han's fix

- src/commands/math.js
- src/services/textarea.js
We need this for the Four Function calculator
> add useDivisionSymbol option

- src/services/aria.js
https://github.com/desmosinc/pillow/issues/7249
https://github.com/desmosinc/knox/issues/6833
> Fix injection vulnerability

- src/commands/math/basicSymbols.js
AIR needs to render these with a custom font.
Note: I couldn't find a latex character code for not parallel
> add in a two Stix Characters

- docs/Api_Methods.md
- docs/Config.md
- src/commands/math.js
- src/commands/math/LatexCommandInput.js
- src/commands/math/advancedSymbols.js
- src/commands/math/basicSymbols.js
- src/commands/math/commands.js
- src/commands/text.js
- src/services/aria.js
- src/services/keystroke.js
- src/services/textarea.js
- test/unit/aria.test.js
- test/unit/publicapi.test.js
This PR includes:
* refactored ARIA alert code with minimal changes to voiced output
* fixed MathQuill tests
* additional ARIA alert tests
Base repository for this work is at sclower/mathquill.
> Refactor ARIA alert code

- src/commands/math.js
- src/commands/math/basicSymbols.js
- src/commands/math/commands.js
- test/unit/typing.test.js
> Add typingPercentWritesPercentOf option.

- src/commands/math/commands.js
- test/unit/typing.test.js
...so that we can use it as an autoCommand
> Alias 'percentof' as 'percent'

- src/services/latex.js
- src/services/textarea.js
we were pruning out spaces in one case but not the other.
> match copy-paste latex to .latex()

- src/commands/math/basicSymbols.js
- test/basic.html
update basic sample page to ensure that they work.
> add "square" and "mid" latex symbols

- src/cursor.js
- src/services/keystroke.js
- src/services/latex.js
- src/services/mouse.js
Attempt to fix same bug as #61 in a way that doesn't need #67 (which was causing other acceptance test failures in Desmos).
> Rework stale selection fix

- src/commands/math/commands.js
- test/unit/typing.test.js
> add typingSlashCreatesNewFraction option

- src/services/scrollHoriz.js
(1) fix repeated firing of the handlers when already at the right or left side
(2) look at blurred for real instead of looking for cursor (didn't take into account selection)
(3) get rid of unnecessary jQuery
> horizontal scroll fixes

- src/publicapi.js
> scrollHoriz even for non-command keys

- src/services/focusBlur.js
- test/unit/resetCursorOnBlur.test.js
Resets the cursor to end of mathquill on blur
> add resetCursorOnBlur option. 

- src/publicapi.js
Useful in conjunction with overrideKeystroke.
> Allow passing an event to keystroke.

- src/commands/math/advancedSymbols.js
- src/commands/math/commands.js
- src/css/math.less
modified longleftrightarrow command to support line
> add support for double arrow line operator

- src/commands/math/commands.js
- src/css/math.less
- test/air-demo.html
> add support for overarc

- src/css/math.less
works better against non-white backgrounds
> use semi-transparency instead of gray

- src/commands/math/basicSymbols.js
This will make dot syntax look nicer
> do not add spacing between letters and period

- src/services/mouse.js
reported here: https://github.com/desmosinc/knox/issues/8582
> fix mouse selection of parens and sqrts within denominators

- src/css/math.less
fixes display with any color except black
> inherit color for underline/overline

- src/commands/math/basicSymbols.js
- test/unit/typing.test.js
typing ~~ gives you the ≈ character. backspace takes you back to tilde
> Add support for approx

- src/publicapi.ts
- src/services/aria.ts
- src/services/saneKeyboardEvents.util.ts
- src/services/textarea.ts
- src/shared_types.d.ts
- src/tree.ts
- src/utils.ts
Type the global "jQuery" variable (previously "any") and fixup uses of methods we have already removed
> Type the global "jQuery" variable

- src/mathquill.d.ts
- src/publicapi.ts
- Return self from setters
- Pull out "InternalMathQuillInstance" as its own interface
- Add missing moveToLeftEnd() method
> Fixup public types

- Makefile
- benchmark/update.html
- src/services/latex.ts
To run this, do
```
make benchmark
open benchmark/update.html
```
Designed to measure how much of a difference `renderLatexMathEfficiently` makes.
> Add benchmark of decimal update performance

- src/commands/math/commands.ts
> Fix vec command

- src/services/saneKeyboardEvents.util.ts
In Linux and Chrome or Chrome OS, users may issue the Ctrl-Shift-U command to input a Unicode character. Unfortunately, when the system is in this state, Chrome sends a keydown of "Ctrl-Shift-Unidentified" in Linux, "Ctrl-Shift-U" on Windows/Mac, or "Ctrl-Shift-Process" in the latest Chrome OS. Equally vexing is that the keyup correctly comes back as Ctrl-Shift-U. Furthermore, an input event with the value "u" is still processed in Linux and Chrome OS due to the down/up mismatch. The end result is that a spurious "u" is sent followed by the intended character.
Due to how this feature works, it's vital to completely ignore Ctrl-Shift-U no matter how the input event appears to Mathquill as clearing the textarea by mistake breaks the expected input flow.
I have verified this works in Ubuntu …
> Work around Linux and Chrome Unicode entry bug

- src/publicapi.ts
StaticMath fields can be selectable, and being able to set selection programmatically can be helpful.
> add "select" and "clearSelection" methods to api for StaticMath fields

- src/mathquill.d.ts
this makes mathquill.d.ts match the publicapi file
> the "selection" method is available on static math

- src/commands/math/basicSymbols.ts
- test/unit/css.test.js
- test/unit/digit-grouping.test.js
this way we can add a little padding after them (starting just with evaluations)
> add a custom class on commas
